apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    networking.knative.dev/disableAutoTLS: "true"
  creationTimestamp: null
  name: elliptical
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      name: elliptical-a13dddc6-4036-4191-a536-8ca7bc4d5060
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: Activity_Name
          value: elliptical
        image: ghcr.io/itsmurugappan/activity
        name: user-container
        ports:
        - containerPort: 0
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources:
          limits:
            cpu: 60m
            memory: 512M
          requests:
            cpu: 30m
            memory: 128M
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
