apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    networking.knative.dev/disableAutoTLS: "true"
  creationTimestamp: null
  name: id
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      name: id-8c1e1db8-19cb-485c-bd2b-23adbc83e53a
    spec:
      containerConcurrency: 0
      containers:
      - image: ghcr.io/itsmurugappan/id
        name: user-container
        ports:
        - containerPort: 0
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources:
          limits:
            cpu: 60m
            memory: 512M
          requests:
            cpu: 30m
            memory: 128M
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
