apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    networking.knative.dev/disableAutoTLS: "true"
  creationTimestamp: null
  name: walk
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      name: walk-cee3d470-026a-4d3a-ac63-c419a46deb73
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: Activity_Name
          value: walk
        image: ghcr.io/itsmurugappan/activity
        name: user-container
        ports:
        - containerPort: 0
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources:
          limits:
            cpu: 60m
            memory: 512M
          requests:
            cpu: 30m
            memory: 128M
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
